### ISSUE TITLE
web 模块启动报错

### ISSUE THREAD

**Issue by zcjlq** [chenfromsz/spring-boot-cloud#1]
您好，在学习您的书，下载源码后运行web模块，控制台报No qualifying bean of type [org.springframework.web.client.RestTemplate
查看此类位于spring-web依赖中，通过dependency:tree 查看依赖关系，发现在项目中
[INFO] +- org.springframework.cloud:spring-cloud-starter-feign:jar:1.2.0.RELEASE:compile
[INFO] |  +- org.springframework:spring-web:jar:4.3.2.RELEASE:compile

请您测试一下，谢谢

**Comment by chenfromsz** [comment]
不好意思，因为更新了使用neo4j的方法而升级了Spring Boot的版本，而相关的RestTemplate的使用方法没有做相应的更新，所以导致了你上面提到的错误。现在已经将代码提交了，你再更新一下，就能正常启动和访问了。
主要是在自动配置中增加如下的配置，简便起见，放在入口程序中：
@Bean
    @LoadBalanced
    RestTemplate restTemplate() {
        return new RestTemplate();
    }
给你造成的不便，请你包涵，谢谢！
