### ISSUE TITLE
data模块docker启动报错

### ISSUE THREAD

**Issue by zcjlq** [chenfromsz/spring-boot-cloud#2]
您好，data模块使用idea启动正常，部署到docker后启动报错，报错部分如下
`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'profileController' defined in URL [jar:file:/app.jar!/BOOT-INF/lib/spring-data-rest-webmvc-2.5.2.RELEASE.jar!/org/springframework/data/rest/webmvc/ProfileController.class]: Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'resourceMappings' defined in class path resource [org/springframework/boot/autoconfigure/data/rest/SpringBootRepositoryRestMvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.rest.core.mapping.RepositoryResourceMappings]: Factory method 'resourceMappings' threw exception; nested exception is java.lang.IllegalArgumentException: PersistentEntity must not be null!; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'resourceMappings' defined in class path resource [org/springframework/boot/autoconfigure/data/rest/SpringBootRepositoryRestMvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.rest.core.mapping.RepositoryResourceMappings]: Factory method 'resourceMappings' threw exception; nested exception is java.lang.IllegalArgumentException: PersistentEntity must not be null!`
google查到以下内容：[https://github.com/spring-projects/spring-boot/issues/4907](url)，能否帮忙看下这个错误，或者您升级spring boot版本看一下。
我的运行环境：mac os ，jdk8，Docker version 17.06.2-ce
谢谢

**Comment by chenfromsz** [comment]
这是由于Spring Boot与Neo4j之中的版本问题引起的，而且在存储库中最好也不要使用这个方式@RepositoryRestResource来调用，因为这里面还有一些不够令人满意的地方。所以这个工程的程序都做了一些更新，并且解决了data模块不能在Docker上发布的问题。对于这个例子，现在最好的方法是使用@RestController与@FeignClient结合使用，有关这种方法的设计，可以参考我的一篇博客文章的介绍：https://my.oschina.net/syic/blog/838651，里面有详细的说明，希望对你有所帮助。
